spring.application.name=sales-service
server.port=8084

# Configuración de Base de Datos para Ventas
spring.datasource.url=jdbc:mysql://localhost:3306/ferreteria_ventas
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desactivar Open-In-View para eliminar la advertencia de los logs
spring.jpa.open-in-view=false