spring.application.name=customer-service
server.port=8082

# Configuración de Base de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/ferreteria_clientes
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desactivar cosas para evitar problemas de rendimiento 
spring.jpa.open-in-view=false